FROM node:8.11.4-alpine as build

COPY package*.json ./
COPY src ./src

RUN apk add --no-cache curl make gcc g++ python linux-headers binutils-gold gnupg libstdc++ git
RUN npm install

FROM node:8.11.4-alpine

RUN apk update
RUN apk add --no-cache curl jq

WORKDIR /opt/pillowboard

COPY package*.json ./
COPY --from=build node_modules/ ./node_modules

EXPOSE 3000

CMD npm start
